### ISSUE TITLE
I can't make the change work checking frequency in config.yaml

### ISSUE THREAD

**Issue by tcssh211065** [HitomaruKonpaku/twspace-crawler#79]
i make the checking interval from 30000 to 300000(30sec to 300sec), but it keep using the initial settings

# The time, in milliseconds, the timer should delay in between checks
interval: 300000

**Comment by HitomaruKonpaku** [comment]
How do run the app btw?

**Comment by tcssh211065** [comment]
twspace-crawler --env ./.env --config ./config.yaml --force-open

**Comment by tcssh211065** [comment]
and my yaml is 
```
# The time, in milliseconds, the timer should delay in between checks
interval: 300000

# ffmpeg extra args
# ffmpegArgs:
#   - -y

# List of user to check for live Spaces
users:
# hololive staff
  - achan_UGA
  - harusakinodoka
  # hololive jp
  - tokino_sora
  - robocosan
  - sakuramiko35
  - suisei_hosimati
  - AZKi_VDiVA
  - yozoramel
  - shirakamifubuki
  - natsuiromatsuri
  - 7216_2nd
  - akirosenthal
  - akaihaato
  - minatoaqua
  - murasakishionch
  - shionchan_o
  - nakiriayame
  - yuzukichococh
  - oozorasubaru
  - ookamimio
  - nekomataokayu
  - MO_OKAYU_GU
  - inugamikorone
  - usadapekora
  - uruharushia
  - shiranuiflare
  - shiroganenoel
  - houshoumarine
  - amanekanatach
  - kiryucoco
  - tsunomakiwatame
  - tokoyamitowa
  - himemoriluna
  - yukihanalamy
  - momosuzunene
  - shishirobotan
  - manoaloe
  - omarupolka
  - LaplusDarknesss
  - takanelui
  - hakuikoyori
  - sakamatachloe
  - kazamairohach
  - hiodoshiao
  - otonosekanade
  - ichijouririka
  - juufuuteiraden
  - todoroki_hajime
  # hololive en
  - moricalliope
  - takanashikiara
  - ninomaeinanis
  - gawrgura
  - watsonameliaEN
  - irys_en
  - tsukumosana
  - ceresfauna
  - ourokronii
  - nanashimumei_en
  - hakosbaelz
  - omegaalpha_en
  - fuwamoco_en
  - nerissa_en
  - kosekibijou
  - shiorinovella
  # hololive id
  - ayunda_risu
  - moonahoshinova
  - airaniiofifteen
  - kureijiollie
  - anyamelfissa
  - pavoliareine
  - vestiazeta
  - kaelakovalskia
  - kobokanaeru
  # other oversea tuber
  - 8HaChi_hacchi
  - ui_shig
  - milkyqueen_idol
  - amsrntk3
  - LichVtuber
  - AmemiyaNazuna
  - mgmgoi4
  - rurudo_
  - nana_kaguraaa
  #soul
  - whatweneed8837
  - NKOK_15
  - NKOK__S
  - DEMONDICEKaren
  - kuroneko_datenn
  - canan8181
  - ksononair
  - 95rn16
  - NNNrm28
  - vKOZUv
  #nijisanji
  - inui_toko
  - amamiya_kokoro 


  # Webhooks
webhooks:
  discord:
  - _name: 'sample'
    active: true
    urls:
    - https://discord.com/api/webhooks/xxx
    # Send webhooks by filtered users
    usernames:
    - <all>
    # Legacy option, use startMessage and/or endMessage instead
    # mentions:
    #   roleIds:
    #   - 'xxx'
    #   userIds:
    #   - 'xxx'
    # Message to send when Space start/running
    # startMessage: ''
    # Message to send when Space ended
    # endMessage: ''
    ```
